#!/bin/bash
dnf install epel-release -y
dnf update  -y
dnf upgrade -y
dnf update  -y
dnf install snapd -y
systemctl enable --now snapd.socket
ln -s /var/lib/snapd/snap /snap
dnf install kernel-modules -y

