#!/bin/bash
mkdir  -p         /etc/TLSCrtManager
cat    << 'EOF' > /etc/TLSCrtManager/Cnf
{
    "LetsEncrypAcntEmail" : "",
    "Domains": [
        {
            "Id": "",
            "PrmryDomain" : "",
            "ScndryDomain": [
                ""
            ],
            "KeyExportPath": "",
            "CrtExportPath": ""
        }
    ]
}
EOF
mkdir  -p   /etc/TLSCrtManager/Dmn
exctnOtcmGrade=$(command -v certbot)
while [ "$exctnOtcmGrade" == "" ] ; do
	snap install certbot --classic
	exctnOtcmGrade=$(command -v certbot)
done
wget "https://github.com/static-web-server/static-web-server/releases/download/v2.33.1/static-web-server-v2.33.1-x86_64-unknown-linux-gnu.tar.gz"
 tar -xvf static-web-server-v2.33.1-x86_64-unknown-linux-gnu.tar.gz
  cp      static-web-server-v2.33.1-x86_64-unknown-linux-gnu/static-web-server /bin/sws
  rm  -rf static-web-server*
