#!/bin/bash
trap "echo 'TLSCrtManager installation failed'; exit 1" ERR
if [ "$1" == "" ]; then
	echo "Email address to use to create LetsEncrypt account not provided"
	exit 1
fi
################################################################################################
# 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012 #
################################################################################################
##### -------------------------
dnf   install bind-utils wget -y
cp         pack/TLSCrtManager-1.x.x/TLSCrtManager          /bin/TLSCrtManager
cp         pack/TLSCrtManager-1.x.x/TLSCrtManager-Update   /bin/TLSCrtManager-Update
chmod 0700 /bin/TLSCrtManager
chmod 0700 /bin/TLSCrtManager-Update
mkdir -p   /bin/TLSCrtManager.Extnsn
cp    -r   pack/TLSCrtManager-1.x.x/TLSCrtManager.Extnsn/* /bin/TLSCrtManager.Extnsn/
chmod 0700 /bin/TLSCrtManager.Extnsn
chmod 0700 /bin/TLSCrtManager.Extnsn/*
##### -------------------------
mkdir -p   /etc/TLSCrtManager
chmod 0700 /etc/TLSCrtManager
if [ ! -f "/etc/TLSCrtManager/Cnf" ] ; then
cat   << 'EOF' > /etc/TLSCrtManager/Cnf
{
    "LetsEncrypAcntEmail" : "",
    "Domains": [
        {
            "Id": "",
            "PrmryDomain" : "",
            "ScndryDomain": [
                ""
            ],
            "KeyExportPath": "",
            "CrtExportPath": ""
        }
    ]
}
EOF
fi
chmod 0600 /etc/TLSCrtManager/Cnf
mkdir -p   /etc/TLSCrtManager/Dmn
chmod 0700 /etc/TLSCrtManager/Dmn
##### -------------------------
trap - ERR
exctnOtcmGrade=$(command -v certbot)
while [ "$exctnOtcmGrade" == "" ] ; do
	snap install certbot --classic
	exctnOtcmGrade=$(command -v certbot)
done
certbot register --agree-tos -n -m "$1"
trap "echo 'TLSCrtManager installation failed'; exit 1" ERR
wget "https://github.com/static-web-server/static-web-server/releases/download/v2.33.1/static-web-server-v2.33.1-x86_64-unknown-linux-gnu.tar.gz" -q
tar -xvf    static-web-server-v2.33.1-x86_64-unknown-linux-gnu.tar.gz
cp          static-web-server-v2.33.1-x86_64-unknown-linux-gnu/static-web-server /bin/sws
rm   -rf    static-web-server*
mkdir -p   /var/tmp/TLSCrtManager/.well-known/acme-challenge
chmod 0777 /var/tmp/TLSCrtManager
