#!/bin/bash
trap "echo 'TLSCrtManager installation failed'; exit 1" ERR
################################################################################################
# 12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012 #
################################################################################################
##### -------------------------
dnf install epel-release -y
dnf update  -y
dnf upgrade -y
dnf update  -y
dnf install snapd -y
systemctl enable --now snapd.socket
trap - ERR
ln -s /var/lib/snapd/snap /snap
trap "echo 'TLSCrtManager installation failed'; exit 1" ERR
dnf install kernel-modules -y
