#!/bin/bash
trap "echo 'Failed.'; exit 1" ERR
###########
rm    -rf  /etc/letsencrypt/archive/*
rm    -rf  /etc/letsencrypt/live/*
rm    -rf  /etc/letsencrypt/renewal/*
mkdir -p  "/etc/TLSCrtManager/tls/$1"


